### ISSUE TITLE
Spotify needs paxmark

### ISSUE THREAD

**Issue by orsonteodoro** [terlar/docker-spotify-pulseaudio#12]
I cannot use this on the host if the host is using a hardened kernel with grsecurity.

paxctl -C spotify
paxctl -z spotify
paxctl -m spotify

https://launchpad.net/ubuntu/+source/paxctl

**Comment by terlar** [comment]
I am not familiar with `grsecurity` and how to utilize it. Are those commands something that is needed to get it working?

**Comment by orsonteodoro** [comment]
Yes but full path to the executable.  I've already made my docker image and can confirm, but it has broken audio.  If you run Arch Linux with hardened kernel, Alpine Linux, Gentoo Hardened, then the container you provided won't work.
