### ISSUE TITLE
Username and password are not remembered

### ISSUE THREAD

**Issue by PabloCastellano** [terlar/docker-spotify-pulseaudio#5]
Every time I start spotify running the script I have to enter my username and password, which is a little annoyance.

**Comment by terlar** [comment]
I agree, I have yet to find a workaround for this, I tried mounting with the file that specifies this, but no luck so far. Also to get the facebook-login work with the external browser somehow would be nice.

**Comment by void32** [comment]
I guess that if you import / export the /data/config/spotify/ folder on startup / shutdown you could preserve the login info and the easiest way to do this is probably to mount a folder as a docker volume.

**Comment by void32** [comment]
I just noticed, you have solved this issue... :-)

**Comment by terlar** [comment]
Verified that this works, thanks 👍
